server:
  port: 8080
  shutdown:
    grace-period: 20000 # 최대 20초 대기후 어플리케이션 down

# actuator
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        #include: refresh
  server:
    port: 8888

logging:
  level:
    root: INFO
  pattern:
    console: '%date - %-5p %t %-25logger{5} %F:%L %m%n'
    file: '%date - %-5p %t %-25logger{5} %F:%L %m%n'
  file:
    path: logs/application.log
    max-history: 1
    max-size: 10

---
#Dev

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: spring
    password: spring
    hikari:
      maximum-pool-size: 250

logging:
  level:
    com.cloud.springcloudweb: DEBUG